; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
custom_version = 0.0.2
custom_ota_repo = davidvancl/project-ikarus
build_flags =
	-DFW_VERSION=\"${this.custom_version}\"
	-DOTA_REPO=\"${this.custom_ota_repo}\"
lib_deps =
	https://github.com/davidvancl/esp-ota-updater.git#v1.0.1
	bblanchon/ArduinoJson@^7.2.2
	wayoda/LedControl@^1.0.6
